name: Toms3DataSender
version: '1.0'
main: io.github.Cherryh4ck.toms3DataSender.Toms3DataSender
api-version: '1.21'
authors: [ Cherryh4ck ]
description: Data sender for toms3.cc website

depend: ["PlaceholderAPI"] #